### ISSUE TITLE
error when trying to use cargo make test with ecs

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/bottlerocket-test-system#653] opened 2022-11-08 05:41 UTC
- using `cargo make -e TESTSYS_TARGET_REGION=us-west-2 -e BUILDSYS_VARIANT=aws-ecs-1 -e BUILDSYS_ARCH=x86_64
  test`
- Using an EKS cluster as my testsys cluster
- Added adminstrator permissions to the EKS nodegroup role
- Cluster creation succeeded `x86-64-aws-ecs-db97d616-ea7f-4472-975a-f114a2d19ed8-creatizv2bb   0/1     Completed`
- Instance creation failed:

```
[2022-11-08T05:33:53Z INFO  resource_agent::agent] Initializing Agent
[2022-11-08T05:33:53Z INFO  ec2_resource_agent::ec2_provider] Beginning instance creation with instance UUID: 08eb220a-4588-4711-ab9d-9b18fc35e8f5
[2022-11-08T05:33:54Z INFO  ec2_resource_agent::ec2_provider] Creating 2 instance(s)
[2022-11-08T05:33:54Z INFO  ec2_resource_agent::ec2_provider] Using instance type 'm5.large'
Provider error: An error occurred but no resources were left behind, Failed to create instances of any of the provided types in any of the provided subnets
```

I'm not sure the easiest way to report testsys version, but my Bottlerocket sha is `01d3a63`.

Two issues, that the error happened, and that the error doesn't tell me anything. There's literally no way to guess what happened.

**Comment by webern** [comment] 2022-11-08 17:25
I think this is the issue with the error messages. When using anyhow::Error we need to print Debug, not Display. anyhow prints only the "top" error message for display, and prints a nicely formatted pseudo stack trace of chained error with Debug.

https://github.com/bottlerocket-os/bottlerocket-test-system/blob/513f71ccb873f889581166d55c1e864f6f596e36/bottlerocket/agents/src/bin/ecs-test-agent/main.rs#L277

Edit: actually looking at the agents, I forgot that it's more complicated than that because of the trait-defined error types. Looking at this.

Edit: oh ok, I see the actual issue. We loop and apparently I can't see any of the errors during the loop, then we fail with this unhelpful message after the looping is done. https://github.com/bottlerocket-os/bottlerocket-test-system/blob/513f71ccb873f889581166d55c1e864f6f596e36/bottlerocket/agents/src/bin/ec2-resource-agent/ec2_provider.rs#L247

This is pretty terrible.

I don't understand why I didn't get any of the `warn!` messages.

**Comment by mjsterckx** [comment] 2022-11-08 20:38
https://github.com/bottlerocket-os/bottlerocket-test-system/blob/513f71ccb873f889581166d55c1e864f6f596e36/bottlerocket/agents/src/bin/ec2-resource-agent/ec2_provider.rs#L221
Since this line was never printed, I don't think the problem is with the `warn!` messages but rather the fact that the inner loop was never executed. In other words. `subnet_ids` could have been empty. I'll look further into that.

Edit: After checking the `ecs_resource_agent` CRD, I noticed that `publicSubnetIds` is populated but `privateSubnetIds` is not. The `ec2_resource_agent` pulls its `subnetIds` from `ecs_resource_agent`'s `privateSubnetIds`, so it was indeed empty and the inner loop didn't run a single time, which is why no errors or warnings were printed. Some more discussion is needed about a possible fix/remedy.

**Comment by ecpullen** [comment] 2022-11-11 00:01
I believe the behavior was changed in https://github.com/bottlerocket-os/bottlerocket/commit/6f5f84d624e906dfc1d067b6358197c8dd7fbd98 to move from public subnets to private subnets. A user using their own vpc would not experience the change, but a user using the default vpc would not be able to launch because the default VPC has no private subnet ids. This should be fixed as part of the refactor in https://github.com/bottlerocket-os/bottlerocket/pull/2560.

**Comment by ecpullen** [comment] 2022-11-28 17:52
This was fixed in https://github.com/bottlerocket-os/bottlerocket/pull/2560.

**Closed as completed by ecpullen** 2022-11-28 17:52 UTC
Labels: bug
